# Generated by Django 3.1.2 on 2020-10-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('DSSRT', 'Dessert'), ('LNCH', 'Lunch'), ('BKFT', 'Breakfast'), ('DNR', 'Dinner')], default='DSSRT', max_length=255),
        ),
    ]
