# Generated by Django 3.1.2 on 2020-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201026_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('BKFT', 'Breakfast'), ('LNCH', 'Lunch'), ('DNR', 'Dinner'), ('DSSRT', 'Dessert')], default='DSSRT', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
