# Generated by Django 3.1.2 on 2020-10-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201026_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='temperature',
            field=models.CharField(choices=[('C', 'Celcius'), ('F', 'Fahrenheit')], default='F', max_length=255),
        ),
    ]
