# Generated by Django 3.1.2 on 2020-10-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201027_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='isPublic',
            new_name='is_public',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('DNR', 'Dinner'), ('BKFT', 'Breakfast'), ('LNCH', 'Lunch'), ('DSSRT', 'Dessert')], default='DSSRT', max_length=255),
        ),
    ]
